### ISSUE TITLE
[Menu] Custom render icon size

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#561] opened 2018-02-02 00:18 UTC
### Expected behavior

Data-Driven - Custom rendar icon size: 24x24
Menu hover, active color: see (https://github.com/mineral-ui/mineral-ui/issues/557)

### Current behavior

Data-Driven - Custom rendar iconsize: 32x32

**Comment by kylegach** [comment] 2018-04-11 19:59
Duplicate of #557 (with same resolution).

**Closed by kylegach** 2018-04-11 19:59 UTC
Labels: design
