### ISSUE TITLE
[Button Default] Replace default button style

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#697] opened 2018-05-16 22:04 UTC
### Current behavior
The current button's default design has lack of using theme color and gray background look doesn't harmonious with other UI elements. 

### Possible solution
Design Spec: https://preview.uxpin.com/871cc8a4f408b19ba0af468631cd762258212741#/pages/83008276/comment/comments?mode=i

Button Text color: theme-60

Default background color: white
Default border color: gray-40

Hover background color: gray-10
Hover border color: theme-50

Active background color: gray 20
Active border color: theme-50

Focus background color: white
Focus border color: gray-40
Focus outline color: theme-70

Disable: not change

**Comment by asagray** [comment] 2018-05-16 22:15
Default/focus background color should be white, in case the button is placed on non-white surfaces.

**Comment by jeeyoung** [comment] 2018-05-16 22:31
updated! thanks

**Comment by VictoriaVasys** [comment] 2018-05-25 17:51
Thanks for calling out these diffs; it's much more helpful than trying to figure out what changed on UXPin.

Going forward, it would be even more helpful to provide tokens instead of aliases (tokens & the aliases they point to can be found in `colorAliases.js` in mineral-ui). This makes updating the code much simpler & will help us all to be more systems-oriented. For example, above you list "Active border color: theme-50", whereas our token for `borderColor_brand_active` points to a value of `brand_70` (`brand` is translated to `theme` in the library). Do you want me to update the token value to `brand_50`, or was that a mistake?

**Comment by jeeyoung** [comment] 2018-05-29 17:47
The active value should be brand_50 which is same as hover value.
brand_70 is only for focus value (outline)

**Comment by VictoriaVasys** [comment] 2018-05-30 16:07
Blocked by lack of clarity re: changes to the whole design system (tokens need to be considered).

**Comment by asagray** [comment] 2018-06-11 21:46
Here's the revised spec using the tokens. The color values are pulled from `colorAliases.js` 

Please review, and if there are no questions, unblock and implement.

Button Text color: `Button_color: color_brand`

Default background color:  `Button_backgroundColor: white`
Default border color: `unchanged`

Hover background color: `Button_backgroundColor_hover: backgroundColor_hover`
Hover border color: `new token: borderColor_brand_hover`

Active background color: `Button_backgroundColor_active: backgroundColor_active`
Active border color: `new token: borderColor_brand_active` (brand-70 - changed from previous issue)

Focus background color: `Button_backgroundColor: white`
Focus border color: `unchanged`
Focus outline color: `unchanged`

Disabled: `unchanged`

**Comment by VictoriaVasys** [comment] 2018-06-11 22:29
@asagray Thanks for the update!

I have a couple clarifying questions: 
* You say "Active border color: new token: borderColor_brand_active (brand-70 - changed from previous issue)"; By "previous issue," do you mean the original issue above?
* A couple times you state `new token`, yet those tokens both exist; did you mean to say new value? If yes, it would help if you edit your comment with those values & provide any additional changes that those token changes will have on other components.
* Based on this issue, we will not be changing the disabled button styles; we're assuming that you're experimenting with related specs on UXPin and that the disabled styles for Button are up-to-date: https://mineral-ui.com/components/button#default (`backgroundColor_disabled = 'gray_30'` and `color_disabled = 'gray_50'`). If this is not true, please update this issue or create a new one with all the changes that will need to take place when those tokens change.

**Comment by asagray** [comment] 2018-06-11 23:06
@VictoriaVasys 

1. correct. We changed the value to match existing components
2. I mean "use this token value" for this intention. I didn't find it in the list on the Button page for default button.
3. Correct. No changes to disabled. I wlll verify in the Sketch file we're using colors consistently. Likely we made a mistake.

Thanks for checking in!

**Comment by jeeyoung** [comment] 2018-06-11 23:49
@VictoriaVasys 
We have found that when buttons and text input are disabled, it used different background colors. So we decided to use the same background color.

Here is the updated value for disable status.

backgroundColor_disabled: gray-20 (original: gray-30)
input_backgroundColor_disabled: unchanged (gray-30)
color_disabled: unchanged (gray-50)

**Comment by VictoriaVasys** [comment] 2018-06-12 17:53
Great, thanks for all the clarifications @asagray & @jeeyoung. I will pick this back up this week & send a link to our PR in the flowdock channel. Perhaps you two could both review the visual (happo) diffs to ensure that the resulting changes are carried through as intended?

**Comment by VictoriaVasys** [comment] 2018-09-13 16:07
`TabItem_borderColor_selected` should match new default Button border color

**Comment by VictoriaVasys** [comment] 2018-09-21 18:21
@jeeyoung @asagray I'm jumping back on this issue and need a clarification/reminder: our current styles have `borderColor_theme_active` with a value of `theme_70` and I can't tell from the issue and discussion above whether we all decided it should stay that way (in which the default Button would have `theme_70`) or whether both should change to `brand_50`.

I thought we landed on `theme_70` (that's what the spec has), but just wanted to double-check.

**Closed** 2018-09-27 17:53 UTC
Labels: in progress
