### ISSUE TITLE
[Dropdown] when forced open, re-renders on document click

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#548] opened 2018-01-26 17:42 UTC
dropdown should probably only rerender if the props change

**Comment by brentertz** [comment] 2018-01-30 14:48
@coldpour When reporting issues, please follow the issue template. You have not provided enough context to make this issue easily actionable.

Under what scenarios does this occur?  When it is open, when it is closed, both?  How can it be reproduced, etc.

**Comment by brentertz** [comment] 2018-02-01 17:43
I don't believe this to be a problematic issue as it is really only exposed in our demo because we force some of the examples to always be open using isOpen=true.  Will users do this?  Maybe.  I don't know.   This value will usually be set from state rather than be hardcoded.  

In any case, when the dropdown is open, document listeners are added to close it on click and on escape.  Clicking therefore calls close.  The re-render is then caused by the `this.setState({ highlightedIndex: null });` in `Dropdown.close()`.  This is not a big deal, but could be addressed.

**Comment by coldpour** [comment] 2018-02-01 17:53
@brentertz ah, my bad about not following the template... I submitted this issue through waffle.io and had no idea that there was a template to follow

it sounds like you've found it anyway, and that seems like a reasonable explanation to me. perhaps we should close this as "not a bug?"

**Comment by brentertz** [comment] 2018-02-02 19:33
As discussed, this is probably pretty low priority.  I am going to close it for now.  Please feel free to reopen if you need this behavior to change.

**Closed by brentertz** 2018-02-02 19:33 UTC
Labels: bug, component
