### ISSUE TITLE
[Card] Produces flow type errors

### ISSUE THREAD

**Issue by avivash** [mineral-ui/mineral-ui#245] opened 2017-08-08 23:37 UTC
### Expected behavior
No `flow` errors should be present.

### Current behavior
![image](https://user-images.githubusercontent.com/1179291/29098935-d9719306-7c56-11e7-938a-13d133569af7.png)

### Possible solution
Update the `@mineral-ui/card/dist/umd/Card.js.flow` resolve the reference to `MnrlReactNode`.

### Steps to reproduce (for bugs)
1. Install peer dependencies and component into application via `npm i`
2. Run `flow` via `npm run flow` or `flow`, if installed globally.
3. View `flow` errors in the terminal.

### Context
Our application runs the `flow` command on every `npm start` or whenever a file is updated. We can't rely on packages that are introducing `flow` errors into our build.

### Versions

| Component | Version |
| @mineral-ui/card | 1.0.1 |

**Comment by calthomson** [comment] 2017-08-09 00:17
I am also seeing flow errors after importing the Mineral-UI Button component into Phoenix-Dashboard:

![screenshot 2017-08-08 17 15 11](https://user-images.githubusercontent.com/8645285/29099986-78be821a-7c5d-11e7-9190-43290d9835ab.png)

**Comment by coldpour** [comment] 2017-08-09 19:25
duplicate of #78

**Closed by coldpour** 2017-08-09 19:25 UTC
