### ISSUE TITLE
[Radio Group] Minor values change

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#563] opened 2018-02-02 00:37 UTC
### Expected behavior

Padding between Lable and Formfield: 8px padding
Caption: We recommend the location of the caption should below the Label (We can provide the optional variation which is located bottom the the field) see (https://ca.invisionapp.com/d/main#/console/11070131/250302831/preview)

### Current behavior

Padding between Lable and Formfield: 7px padding
Caption: located bottom of the field
### Possible solution
Needs to change the correct color values

**Comment by kylegach** [comment] 2018-04-11 20:00
Duplicate of #556.

**Closed by kylegach** 2018-04-11 20:00 UTC
Labels: design
